channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.4.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - certifi=2024.7.4
  - charset-normalizer=3.3.2
  - comm=0.2.2
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.6.37
  - cuda-runtime=12.1.0
  - cuda-version=12.6
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - ffmpeg=4.3
  - freetype=2.12.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.8
  - intel-openmp=2023.1.0
  - ipython=8.26.0
  - ipywidgets=8.1.5
  - jedi=0.19.1
  - jinja2=3.1.4
  - jpeg=9e
  - jupyterlab_widgets=3.0.13
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.11.0.15
  - libcurand=10.3.7.37
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.14
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - prompt-toolkit=3.0.47
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.11.9
  - pytorch=2.4.0
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - readline=8.2
  - requests=2.32.3
  - setuptools=72.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - sympy=1.12.1
  - tbb=2021.8.0
  - tk=8.6.14
  - torchaudio=2.4.0
  - torchtriton=3.0.0
  - torchvision=0.19.0
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - urllib3=2.2.2
  - wcwidth=0.2.13
  - wheel=0.43.0
  - widgetsnbextension=4.0.13
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstandard=0.22.0
  - zstd=1.5.5
  - pip:
      - accelerate==0.33.0
      - addict==2.4.0
      - aider-chat==0.55.0
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.4.0
      - attrs==24.2.0
      - backoff==2.2.1
      - beautifulsoup4==4.12.3
      - bitsandbytes==0.43.3
      - cffi==1.17.0
      - cfgv==3.4.0
      - click==8.1.7
      - configargparse==1.7
      - contourpy==1.3.0
      - cycler==0.12.1
      - datasets==2.21.0
      - debugpy==1.8.5
      - deepspeed==0.15.1
      - diff-match-patch==20230430
      - dill==0.3.8
      - diskcache==5.6.3
      - distlib==0.3.8
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - einops==0.8.0
      - filelock==3.15.4
      - flake8==7.1.1
      - flash-attn==2.6.3
      - fonttools==4.53.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - grep-ast==0.3.3
      - groq==0.11.0
      - h11==0.14.0
      - hf-transfer==0.1.8
      - hjson==3.1.0
      - httpcore==1.0.5
      - httpx==0.27.2
      - huggingface-hub==0.24.6
      - hydra-core==1.3.2
      - identify==2.6.0
      - importlib-metadata==7.2.1
      - importlib-resources==6.4.4
      - iniconfig==2.0.0
      - ipykernel==6.29.5
      - jiter==0.5.0
      - joblib==1.4.2
      - json5==0.9.25
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - kiwisolver==1.4.7
      - litellm==1.44.7
      - loguru==0.7.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mccabe==0.7.0
      - mdurl==0.1.2
      - multidict==6.0.5
      - multiprocess==0.70.16
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - ninja==1.11.1.1
      - nodeenv==1.9.1
      - omegaconf==2.3.0
      - openai==1.42.0
      - packaging==24.1
      - pandas==2.2.2
      - pathspec==0.12.1
      - peft==0.12.0
      - platformdirs==4.2.2
      - pluggy==1.5.0
      - pre-commit==3.8.0
      - protobuf==3.20.3
      - psutil==6.0.0
      - py-cpuinfo==9.0.0
      - pyarrow==17.0.0
      - pycodestyle==2.12.1
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pyflakes==3.2.0
      - pypandoc==1.13
      - pyparsing==3.1.4
      - pyperclip==1.9.0
      - pytest==8.3.2
      - pytest-mock==3.14.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2024.1
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - referencing==0.35.1
      - regex==2024.7.24
      - rich==13.8.0
      - rpds-py==0.20.0
      - ruff==0.6.5
      - safetensors==0.4.4
      - scikit-learn==1.5.1
      - scipy==1.13.1
      - sentencepiece==0.2.0
      - sentry-sdk==2.13.0
      - setproctitle==1.3.3
      - setuptools-scm==8.1.0
      - shtab==1.7.1
      - smmap==5.0.1
      - sniffio==1.3.1
      - sounddevice==0.5.0
      - soundfile==0.12.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - threadpoolctl==3.5.0
      - tiktoken==0.7.0
      - tokenizers==0.19.1
      - tornado==6.4.1
      - tqdm==4.66.5
      - transformers==4.44.2
      - tree-sitter==0.21.3
      - tree-sitter-languages==1.10.2
      - trl==0.9.6
      - tyro==0.8.10
      - tzdata==2024.1
      - unsloth==2024.8
      - virtualenv==20.26.3
      - wandb==0.17.7
      - xformers==0.0.27.post2
      - xxhash==3.5.0
      - yarl==1.9.4
      - zipp==3.20.1
