# @package _global_

defaults:
  - /trainer/common/model_kwargs@evaluation.model_kwargs: sdpa
  - /dataset: bert/fact_checking

evaluation:
  class_name: supertrainer.evaluations.bert.BertEvaluation
  classes:
    - REFUTES
    - SUPPORTS
    - NOT_ENOUGH_INFO

  model_name: FacebookAI/xlm-roberta-base

dataset:
  class_name: supertrainer.data.fact_checking.FactCheckingBERTEvaluationDataset
  dataset_kwargs:
    path: Erland/fake_news_detection_dataset_cross_lingual_formatted
  tokenizer_name_or_path: ${evaluation.model_name}
