# @package _global_

defaults:
  - /trainer/common/model_kwargs@evaluation.model_kwargs: sdpa
  - /dataset: llm/fact_checking

dataset:
  class_name: supertrainer.data.fact_checking.FactCheckingSonnetEvaluationDataset
  dataset_kwargs:
    path: ./assets_local/formatted_dataset
  tokenizer_name_or_path: ${evaluation.model_name}

evaluation:
  system_prompt: "You are an helpful AI assistant. You are asked to provide a fact-checking response to the following claim:"

  class_name: supertrainer.evaluations.sonnet.SonnetEvaluation
  classes:
    - REFUTES
    - SUPPORTS
    - NOT_ENOUGH_INFO

  batch_name: "sonnet_factcheck"
  batch_dataset: "assets_local/subset_dataset"
  batch_kwargs:
    endpoint: "/v1/chat/completions"
    completion_window: 24h
    metadata:
      description: "Sonnet fact-checking"

  client_kwargs:
    model: "claude-3-5-sonnet-20240620"
    max_tokens: 64
    temperature: 0.8
    top_p: 1
