dataset_kwargs:
  path: Erland/fake_news_detection_dataset_cross_lingual_formatted_uncased

class_name: supertrainer.data.fact_checking.FactCheckingTrainingDataset
subsets:
  - 'train_claim_en_evidence_en'
  - 'train_claim_en_evidence_idn'
  - 'train_claim_en_evidence_arb'
  - 'train_claim_idn_evidence_en'
  - 'train_claim_idn_evidence_idn'
  - 'train_claim_idn_evidence_arb'
  - 'train_claim_arb_evidence_en'
  - 'train_claim_arb_evidence_idn'
  - 'train_claim_arb_evidence_arb'
classes:
  - REFUTES
  - SUPPORTS
  - NOT_ENOUGH_INFO
