defaults:
  - /trainer/common/model_kwargs@model_kwargs: sdpa

class_name: supertrainer.inferences.bert.BERTInference
classes:
  - REFUTES
  - SUPPORTS
  - NOT_ENOUGH_INFO

model_name: google-bert/bert-base-multilingual-uncased
