# defaults:
#   - /trainer/common/model_kwargs@model_kwargs: eager

class_name: supertrainer.inferences.sonnet.SonnetInference
# classes:
#   - REFUTES
#   - SUPPORTS
#   - NOT_ENOUGH_INFO

client_kwargs:
  model: "claude-3-5-sonnet-20240620"
  max_tokens: 1000
  temperature: 0
