class_name: supertrainer.inferences.sonnet.SonnetInstructorInference
classes:
  - REFUTES
  - SUPPORTS
  - NOT_ENOUGH_INFO

system_prompt: "You are an helpful AI assistant. You are asked to provide a fact-checking response to the following claim:"

batch_name: "sonnet_factcheck"
batch_dataset: "assets_local/subset_dataset"
batch_kwargs:
  endpoint: "/v1/chat/completions"
  completion_window: 24h
  metadata:
    description: "Sonnet fact-checking"

client_kwargs:
  model: "claude-3-5-sonnet-20240620"
  max_tokens: 64
  temperature: 0.8
  top_p: 1
