defaults:
  - /trainer/common/model_kwargs@model_kwargs: sdpa
  - /trainer/common/bitsandbytes_kwargs@bitsandbytes_kwargs: nf4
  - /trainer/common/training_kwargs@training_kwargs: default
  - /trainer/bert@peft_kwargs: peft_kwargs
  - _self_

# INSERT ADDITIONAL PARAMS HERE
class_name: supertrainer.trainers.bert_trainer.BERTTrainer
classes:
  - positif
  - negatif
  - netral
# TODO: Find better place for this
model_name: bert-base-uncased

# INSERT OVERRIDE CONFIGS HERE
training_kwargs:
  hub_model_id: "masa-research/bert-preskripsi"
