defaults:
  - _self_
  - override hydra/hydra_logging: default
  - override hydra/job_logging: default


trainer:
  testing: False
dataset:
  testing: False
hydra:
  job:
    name: default
  run:
    dir: ${oc.env:OUTPUT_DIR,./hydra_outputs}/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
