defaults:
  - _self_
  - bitsandbytes_kwargs: nf4
  - model_kwargs: sdpa
  - peft_kwargs: classification
  - training_kwargs: default

class_name: supertrainer.trainers.hf_trainer.BERTTrainer
classes: 
  - positif
  - negatif
  - netral
# TODO: Find better place for this
model_name: bert-base-uncased